version: '3.7'
services:
    postgres-zemond:
      image: postgres:13.2-alpine
      container_name: postgres-zemond
      volumes:
        - ./postgres_data:/var/lib/postgresql/data
  #    ports:
  #      - "5432:5432/tcp"
      networks:
         zemond-nat:
           ipv4_address: 172.25.0.2
      environment:
        - POSTGRES_PASSWORD=psqlpass
        - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/13/bin
        - GOSU_VERSION=1.12
        - LANG=en_US.utf8
        - PG_MAJOR=13
        - PG_VERSION=13.2-1.pgdg100+1
        - PGDATA=/var/lib/postgresql/data
      restart: unless-stopped


networks:
  zemond-nat:
    external: true
    name: zemond-nat
