[supervisord]
nodaemon=true
user=root

[program:rtsp-server]
command=/zemond/rtsp-simple-server /zemond/rtsp-simple-server.yml

[program:ffmpeg-loop]
command=/bin/bash /zemond/camera_ffmpeg.sh

[program:camera-watchdog]
command=/bin/bash /zemond/camera_watchdog.sh
